Vulnerable dependencies chapter
infinum/dotnet-handbook pull request #84
Opened 2023-05-24 12:25 UTC by icottiero

Task: https://app.productive.io/1-infinum/tasks/4821362
- Added a new chapter Vulnerable dependencies with our conclusions from researching how to handle vulnerable packages.

2023-05-24 15:15 UTC, mahrncic requested changes
Great section, I believe it will be useful to read :)
Left a couple of minor suggestions

2023-05-24 15:15 UTC, mahrncic commented on Best practices/Vulnerable dependencies
> +Another important thing to get from a security report is whether a certain vulnerability can be used against our system. If a vulnerability is afflicting a feature that is not being used by our solut
Last sentence of this section `... in which case it we should fix the issue..`, I think that the `it` word should be removed, so we should just say `... in which case we should fix the issue...`. 

Also, at the end of that sentence, it says `... we should fix the issue either by updating the packages.` Why are we using the word `either` if we are only proposing one thing (updating the packages)?

2023-05-24 15:15 UTC, mahrncic commented on Best practices/Vulnerable dependencies
> +This will print all the dependency paths which include the specified package and version. Using that information we can determine which dependencies include the vulnerable one:
`This will print all dependency paths ...` instead of `This will print all the dependency paths...` ?

2023-05-25 06:53 UTC, icottiero commented on Best practices/Vulnerable dependencies
> +Another important thing to get from a security report is whether a certain vulnerability can be used against our system. If a vulnerability is afflicting a feature that is not being used by our solut
Another classic result of iterating through a single sentence 5 times, and then leaving it half-baked without even realizing :)

2023-05-25 07:00 UTC, mahrncic approved these changes

2023-05-25 07:41 UTC, merged