added chapter related to serialization
infinum/dotnet-handbook pull request #87
Opened 2023-09-07 13:54 UTC by rvn42

2023-09-08 10:17 UTC, icottiero requested changes

2023-09-08 10:17 UTC, icottiero commented on Best practices/Serialization & Deserialization.md
> +- [# Try the new System.Text.Json source generator](https://devblogs.microsoft.com/dotnet/try-the-new-system-text-json-source-generator)
Please remove the `#` symbols, since these are bullet points, they will already have a symbol before the text.

2023-09-08 10:17 UTC, icottiero commented on Best practices/Serialization & Deserialization.md
> +Starting from .NET 6, `System.Text.Json` introduced source generators, enhancing serialization performance. This feature can operate in two primary modes: gathering metadata and optimizing serializat
Should we add a couple of sentences describing the motivation for developing Source Generators for serialization?

We should also write about why aren't we using them by default, and in what cases are they useful.

2023-09-08 10:17 UTC, icottiero commented on Best practices/Serialization & Deserialization.md
> +    public partial class MyJsonContext : JsonSerializerContext { }
If this is a context only for the `WeatherForecast` class, we should name it accordingly.

2023-09-08 11:22 UTC, icottiero commented on Best practices/Serialization & Deserialization.md
> +    public partial class MyJsonContext : JsonSerializerContext { }
I see, but since this was not apparent to me as a reader, then maybe we should add this info here.

2023-09-13 12:39 UTC, jelena-music commented on Best practices/Serialization & Deserialization.md
> +
Maybe we can elaborate this one, what 10 here mean? Can we describe use case when we want 1 to set and when we may need 10 :D

2023-09-13 12:39 UTC, jelena-music commented on Best practices/Serialization & Deserialization.md
> +
Here also, can we add example use cases for each value?

2023-09-14 13:53 UTC, icottiero requested changes
A couple of minor formatting tweaks and we're done.

In addition to these comments, I think that we should rename this section to something like "JSON" or "JSON serialization & deserialization" because there are many more types of serialization, and we're talking only about JSON here.

After resolving these comments, don't forget to add this chapter to the chapters list in the private repo. I think there might be some issues with having the symbol "&" in the name, but we can try to deploy it as is and rename it if we encounter any problems.

2023-09-14 13:53 UTC, icottiero commented on Best practices/Serialization & Deserialization.md
> +var options = new JsonSerializerOptions {
Please fix the formatting - we're not writing Java here :)

2023-09-14 13:53 UTC, icottiero commented on Best practices/Serialization & Deserialization.md
> +1. **ReferenceHandler.Default**: This is the default behavior, where object references are not preserved during serialization. If you have circular references in your object graph, serializing it wit
Add an empty line between the text and the beginning of numbered block, the parser won't show the renumbered list as intended without it.

2023-10-04 16:43 UTC, icottiero approved these changes

2023-10-10 12:18 UTC, jelena-music approved these changes

2023-10-10 14:50 UTC, merged